logging:
  file:
    name: app.log
  level:
    com:
      yourpackage: DEBUG
    root: INFO

spring:
  profiles:
    active: dev

My:
  Name: Jainish

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: demo
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./data/mydb-dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: demo
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  datasource:
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./data/mydb-prod
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
